/**
 * The TaleSpire asset catalog.
 *
 * Shipped with the page, so it works the moment it loads. A slab names assets
 * by id, and asking everyone to go hunting through Program Files for
 * index.json before they can do anything is a poor first minute.
 *
 * The file covers the Medieval Fantasy pack — 2025 assets, 90 KB over the wire
 * once compressed. It is generated by tools/build_catalog.py from an installed
 * copy, and holds only what the page uses: the name and tags for the search
 * ranking, the footprint for the tie-break, the height for the layout, and the
 * set a piece belongs to for the palette to narrow by.
 *
 * Note the axis mismatch, handled by the generator: a pack index is Unity
 * data, where y is up, while the slab format puts the vertical axis on z.
 */

const CATALOG_URL = "./js/catalog.json";

/** Words marking a piece cut for one position in a run rather than for filling
 *  it. Laid down as the whole wall, a corner gives every room the same notched
 *  edge and no rotation can rescue it. */
const POSITION_WORDS = new Set([
  "corner", "corners", "end", "ends", "cap", "diag", "diagonal", "filler",
  "half", "junction", "tjunction", "inner", "outer", "edge", "strip",
]);

export class UnresolvedAsset extends Error {}

const words = (text) => new Set((text.toLowerCase().match(/\w+/g) || []));

/** How wide and how deep, as one word: the thing that decides whether a piece
 *  can stand where a label puts it. */
export const sizeKey = (asset) => asset.footprint.join("x");

export class Catalog {
  constructor(assets) {
    this.assets = assets.slice().sort((a, b) =>
      a.name.toLowerCase().localeCompare(b.name.toLowerCase()) || a.id.localeCompare(b.id)
    );
    this.byId = new Map(this.assets.map((a) => [a.id.toLowerCase(), a]));
  }

  /** The catalog that ships with the page. */
  static async load(url = CATALOG_URL) {
    const response = await fetch(url);
    if (!response.ok) {
      throw new Error(`Could not load the asset catalog (${response.status}).`);
    }
    return new Catalog(await response.json());
  }

  get packs() {
    return [...new Set(this.assets.map((asset) => asset.pack))];
  }

  /** The sets TaleSpire files its own pieces under — "Sewer", "Castle Ruins".
   *  Empty where the assets came from the catalog shipped with the page, which
   *  does not carry them. */
  get groups() {
    return [...new Set(this.assets.map((asset) => asset.group).filter(Boolean))].sort();
  }

  /**
   * The footprints worth choosing between, smallest first.
   *
   * Only those that land on the half-tile grid. Props are measured to the
   * millimetre — a lantern is 0.08 by 0.07 — and listing every one of those
   * gives nine hundred choices that answer no question anyone has. What is left
   * is the two dozen sizes a piece can actually be laid out on, which is the
   * only thing this filter is for; the rest are still reached by searching.
   */
  get sizes() {
    const onGrid = (value) => value > 0 && Math.abs(value * 2 - Math.round(value * 2)) < 1e-9;
    const seen = new Map();
    for (const asset of this.assets) {
      if (asset.footprint.every(onGrid)) seen.set(sizeKey(asset), asset.footprint);
    }
    return [...seen.entries()]
      .sort(([, a], [, b]) => a[0] * a[1] - b[0] * b[1] || a[0] - b[0])
      .map(([key]) => key);
  }

  /**
   * Assets matching some typed words, best first.
   *
   * The same ranking the themes resolve by, exposed for a person to drive: the
   * top of this list is what a theme written with those words would have
   * picked, so choosing by hand starts where choosing by rule left off.
   *
   * Unlimited by default. A picker showing a hundred of three thousand pieces
   * cannot be browsed, only searched, and browsing is the point: the limit is
   * how many are drawn at once, not how many are found.
   */
  search(text, { kind = null, group = null, size = null, limit = Infinity } = {}) {
    const wanted = words(text || "");
    const pool = this.assets.filter(
      (asset) =>
        (!kind || asset.kind === kind) &&
        (!group || asset.group === group) &&
        (!size || sizeKey(asset) === size)
    );
    if (!wanted.size) return Number.isFinite(limit) ? pool.slice(0, limit) : pool;
    const ranked = pool
      .map((asset) => ({ asset, score: searchScore(asset, wanted) }))
      .filter((entry) => entry.score > 0)
      .sort((a, b) => b.score - a.score || comparePlainness(a.asset, b.asset, wanted))
      .map((entry) => entry.asset);
    return Number.isFinite(limit) ? ranked.slice(0, limit) : ranked;
  }

  query({ name = null, kind = null, footprint = null } = {}) {
    const wantedName = name ? name.toLowerCase() : null;
    return this.assets.filter((asset) => {
      if (wantedName !== null && asset.name.toLowerCase() !== wantedName) return false;
      if (kind !== null && asset.kind !== kind) return false;
      if (footprint && (asset.footprint[0] !== footprint[0] || asset.footprint[1] !== footprint[1]))
        return false;
      return true;
    });
  }

  /**
   * Pick exactly one asset, the same one every time.
   *
   * With a keyword search the pick is a ranking rather than a filter, and the
   * ranking is the whole quality of a theme written in words: a phrase like
   * "stone dungeon tile" matches hundreds of assets, so what decides between
   * them decides what the map is built from.
   */
  resolve(spec) {
    const matches = this.query(spec);
    if (!matches.length) throw new UnresolvedAsset(describe(spec));

    if (spec.search) {
      const wanted = words(spec.search);
      if (wanted.size) {
        const scored = matches
          .map((asset) => ({ asset, score: searchScore(asset, wanted) }))
          .filter((entry) => entry.score > 0);
        if (!scored.length) throw new UnresolvedAsset(describe(spec));
        const best = Math.max(...scored.map((e) => e.score));
        const tied = scored.filter((e) => e.score === best).map((e) => e.asset);
        return tied.sort((a, b) => comparePlainness(a, b, wanted))[0];
      }
    }
    return matches.sort((a, b) => a.id.toLowerCase().localeCompare(b.id.toLowerCase()))[0];
  }
}

/**
 * How well an asset answers a set of keywords.
 *
 * Weighted by where the word was found: the name says what an asset IS, while
 * a tag often says only what it sits near. A word found inside a longer one
 * still counts, at half weight, so "wall" keeps finding "Wallbase".
 */
function searchScore(asset, wanted) {
  const name = asset.name.toLowerCase();
  const nameWords = words(name);
  const tagText = asset.tags.join(" ");
  let total = 0;
  for (const word of wanted) {
    if (nameWords.has(word)) total += 4;
    else if (name.includes(word)) total += 2;
    else if (tagText.includes(word)) total += 1;
  }
  return total;
}

/**
 * The tie-break: the plainest asset of those that scored the same.
 *
 * Keyword ties run to hundreds, so this decides most searches. Plainest means
 * something that fits a single cell, then something that covers the cell it is
 * in, then not a piece cut for one position, then the fewest extra words.
 *
 * Fitting is not being square: a wall tile is half a cell deep because it
 * stands on the cell's edge, so a rule wanting exactly 1x1 hands every wall to
 * whichever corner block happens to be a cube.
 */
function comparePlainness(a, b, wanted) {
  const key = (asset) => {
    const longest = Math.max(asset.footprint[0], asset.footprint[1]);
    const tile = asset.kind === "Tiles";
    const unasked = [...words(asset.name)].filter(
      (w) => POSITION_WORDS.has(w) && !wanted.has(w)
    ).length;
    return [
      tile ? (longest <= 1 ? 0 : 1) : 0,
      tile ? (longest === 1 ? 0 : 1) : 0,
      unasked,
      words(asset.name).size,
      asset.name.length,
      asset.id.toLowerCase(),
    ];
  };
  const left = key(a), right = key(b);
  for (let i = 0; i < left.length; i++) {
    if (left[i] < right[i]) return -1;
    if (left[i] > right[i]) return 1;
  }
  return 0;
}

function describe(spec) {
  return `No asset matches ${JSON.stringify(spec)}`;
}
